### ISSUE TITLE
Issues about `make update`

### ISSUE THREAD

**Issue by AllenDang** [AllenDang/cimgui-go#129]
I tried to use `make update` to update imgui and implot and found few issues:
1. `cimplot_templates` seems in wrong path? Currently it locates in `./cimgui/cimplot_tempates`.
2. Wrong brach is checkout for `imgui` in tmp folder, if I `rm -rf tmp` and rerun `make update`, a new brach which is detached from main will be created, and I actually cannot get the newest code from imgui.
3. The `tmp` folder should be deleted after the process, now it will remain still.
4. The `CMakeList.txt` seems be deleted from `./cimgui`, how can I compile it right now?

**Comment by AllenDang** [comment]
@gucio321 Can you take a look?

**Comment by gucio321** [comment]
@AllenDang sure! Let me quickly discuss each of the points above:
> cimplot_templates seems in wrong path? Currently it locates in ./cimgui/cimplot_tempates.

I actually wanted to put all the imgui stuff in one directory so that we don't need to edit includes in cimplot e.t.c.
I suppose, that the name of directory may be a bit missleading (how shall I call it then?)

> Wrong brach is checkout for imgui in tmp folder, if I rm -rf tmp and rerun make update, a new brach which is detached from main will be created, and I actually cannot get the newest code from imgui.

I think I see why it happens - we're actually cloning stuff from cimgui rather than from imgui, and imgui is a submodule of cimgui **and** cimgui isn't always exactly at imgui's master.
Should we switch to imgui's master before generating binding? Note that it may cause cimgui generator's crash sometimes (if something changed unexpectedly inside of imgui)

> The tmp folder should be deleted after the process, now it will remain still.

it could be deleted, but it is included in `.gitignore` so it doesn't matter tbh. Should I edit `Makefile` so that it gets removed immedietly after updating?

> The CMakeList.txt seems be deleted from ./cimgui, how can I compile it right now?

there is a customized `CMakeList.txt` in `lib` directory (workflows have been updated and work as before)

**Comment by AllenDang** [comment]
@gucio321 I see, it's ok to do so.
For imgui update, I think we should update it from imgui's docking branch directly, as cimgui is meant to be able to do binding generation, if things go wrong, we could fix it manually and raise a PR to cimgui, and imgui's release cycle is way shorter than cimgui.

**Comment by gucio321** [comment]
@AllenDang go it, will open a PR soon
what about 1, 3 and 4?

**Comment by AllenDang** [comment]
@gucio321 I'm ok with your decision in 1, 3 and 4 :)

**Comment by gucio321** [comment]
ok, so closing
